### ISSUE TITLE
Config location

### ISSUE THREAD

**Issue by ghost** [Tfarcenim/BotaniaTweaker#2]
(Compiled eb32604 for what it's worth)

Currently, it seems that the configuration file is located in the save folder `.minecraft/saves/world/serverconfig` Would it be possible to move this to the `.minecraft/config` folder so that it takes effect with all saves instead of a per world basis?

Right now, if you make a "test world" of sorts, you need to remember to manually copy over the config file from other worlds. This will also make it difficult for mod packs to ship said config as if someone names thier world differently, it won't take any effect.

**Comment by Tfarcenim** [comment]
/defaultconfigs exist for this purpose, server config was chosen since it syncs from client to server.
