### ISSUE TITLE
Crash when trying to load Minecraft

### ISSUE THREAD

**Issue by ravenbuilder934** [Tfarcenim/BotaniaTweaker#4]
My game keeps CTD before it's fully loaded. It doesn't give an error message.

Crash report: https://gist.github.com/ravenbuilder934/25f11d9f76c39f4a7bb2a06fd5d3bdb7
Latest.log: https://gist.github.com/ravenbuilder934/e9a1569e7434e9f5bab38f4b940b24ad

The Forge people said this was either Botania or Immersive Engineering, then the Immersive Engineering people said it was Botania Tweaker. So now I'm here.

Versions:
Minecraft 1.15.2
Botania Tweaker 1.1a

**Comment by ravenbuilder934** [comment]
It still crashes, even on version 1.2

**Comment by Tfarcenim** [comment]
same log?

**Comment by ravenbuilder934** [comment]
I copied it again: https://gist.github.com/ravenbuilder934/7433b8dc8d29d158cadf3c651e0512e0
Thanks for your prompt response!
